bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only:[:create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update, :index]
  root to: 'home#top'
  get 'home/about' => 'home#about'
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image
  def email_required?
  	false
  end
  def email_changed?
  	false
  end
  has_many :books, dependent: :destroy
  attachment :profile_image
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end
	def after_sign_out_path_for(resource)
		flash[:notice] = 'Signed out successfully.'
		root_path
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def create
    @books = Book.all
	  @book = Book.new(book_params)
	  @book.user_id = current_user.id
	  if @book.save
		redirect_to book_path(@book.id), notice: 'You have created book successfully.'
	  else
		render :index
	  end
	end

	def index
    @book = Book.new
		@books = Book.all
	end

	def show
    @cook = Book.new
		@book = Book.find(params[:id])
    @user = @book.user
	end

  def edit
  	  @book = Book.find(params[:id])
      unless @book.user_id == current_user.id
         redirect_to books_path
      end
  end

  def update
  	  @book = Book.find(params[:id])
  	 if @book.update(book_params)
  	    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
  	 else
  	  	render :edit
  	 end
  end

    def destroy
  	  @book = Book.find(params[:id])
  	  @book.destroy
  	  redirect_to books_path
    end
    private
    def book_params
	  params.require(:book).permit(:title, :body)
    end
end

bookers2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

bookers2/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_inactive_sign_up_path_for(resource)
    user_path(current_user.id)
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
    render :books#index
    end
  end
  def index
    @users = User.all
    @book = Book.new
  end
  def show
  	@user = User.find(params[:id])
  	@books = @user.books.all.reverse_order
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  	   redirect_to user_path(@user.id), notice: "You have updated user successfully."
     else
      render :edit
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/home_helper.rb
module HomeHelper
end

bookers2/app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>Editing Book</h2>
			<%= form_for(@book) do |f| %>
			<% if @book.errors.any? %>
			  <%= @book.errors.count %>errors prohibited this obj from being saved:
			  <ul>
			  <% @book.errors.full_messages.each do |message| %>
			  <li><%= message %></li>
			  <% end %>
			  </ul>
			<% end %>
				<div class="field">
					<h4>Title</h4>
					<%= f.text_field :title %>
				</div>
				<div class="field">
					<h4>Opinion</h4>
					<%= f.text_area :body %>
				</div>
				<div class="actions">
					<%= f.submit 'Update Book' %>
				</div>
			<% end %>

			<%=link_to "Show", book_path(@book) %>
			|
			<%=link_to "Back", books_path %>
		</div>
	</div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container">
<p id="notice">
	<%= notice %>
</p>
<div class="row">
<% if @book.errors.any? %>
	<%= @book.errors.count %>errors prohibited this obj from being saved:
	<ul>
	<% @book.errors.full_messages.each do |message| %>
	<li><%= message %></li>
	<% end %>
	</ul>
<% end %>
<div class="col-xs-3">
<h2>User info</h2>
	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg" %>
	<table class="table table-striped">
			<tr>
				<th>name</th>
				<th><%= current_user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= current_user.introduction %></th>
			</tr>
	</table>
	<div class="row">
		<%= link_to edit_user_path(current_user) do %>
			<div class="col-xs-12 btn btn-default"><i class="fas fa-wrench"></i></div>
		<% end %>
	</div>
<h2>New Book</h2>
<%= form_for(@book, url: books_path) do |f| %>
	<div class="field">
		<h4>Title</h4>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<h4>Opinion</h4>
		<%= f.text_area :body %>
	</div>
	<div class="actions">
		<%= f.submit 'Create Book' %>
	</div>
<% end %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-striped">
	<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
	</tr>
	<% @books.each do |book| %>
	<tr>
		<td>
			<%= link_to user_path(book.user) do %>
			<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>
			<% end %>
		</td>
		<td><%=link_to book.title, book_path(book.id) %></td>
		<td><%= book.body %></td>
	</tr>
	<% end %>
</table>
</div>
</div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container">
<p id="notice">
	<%= notice %>
</p>
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg" %>
	<table class="table table-striped">
			<tr>
				<th>name</th>
				<th><%= @user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= @user.introduction %></th>
			</tr>
	</table>
	<div class="row">
		<%= link_to edit_user_path(@user) do %>
			<div class="col-xs-12 btn btn-default"><i class="fas fa-wrench"></i></div>
		<% end %>
	</div>
<h2>New Book</h2>
<%= form_for(@cook, url: books_path) do |f| %>
	<div class="field">
		<h4>Title</h4>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<h4>Opinion</h4>
		<%= f.text_area :body %>
	</div>
	<div class="actions">
		<%= f.submit 'Create Book' %>
	</div>
<% end %>
</div>
<div class="col-xs-9">
<h2>Book detail</h2>
<table class="table table-striped">
	<tr>
		<td>
			<%= link_to user_path(@user) do %>
			<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %><br>
			<%= @user.name %>
			<% end %>
		</td>
		<td><%= @book.title %></td>
		<td><%= @book.body %></td>
		<% if @user == current_user %>
			<td><%=link_to "Edit", edit_book_path(@book) %></td>
			<td><%=link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか?" %></td>
		<% end %>
	 </tr>
</table>
</div>
</div>
</div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "https://use.fontawesome.com/releases/v5.6.1/css/all.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <strong class="navbar-brand">Bookers</strong>
        </div>
        <div class="collapse navbar-collapse" id="navbarEexample">
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id) do %>
            <i class="fas fa-home"></i><%= "Home" %>
            <% end %>
          </li>
          <li>
            <%= link_to users_path do %>
            <i class="fas fa-user"></i><%= "Users" %>
            <% end %>
          </li>
          <li>
            <%= link_to books_path do %>
            <i class="fas fa-book"></i><%= "Books" %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i><%= "logout" %>
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to root_path do %>
            <i class="fas fa-home"></i><%= "Home" %>
            <% end %>
          </li>
          <li>
            <%= link_to "/home/about" do %>
            <i class="fas fa-link"></i><%= "About" %>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
            <i class="fas fa-edit"></i><%= "sign up" %>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
            <i class="fas fa-sign-in-alt"></i> <%= "login" %>
            <% end %>
          </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <footer></footer>
  </body>
</html>

bookers2/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
        <h2>User info</h2>
        <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <%= @user.errors.count %>errors prohibited this obj from being saved:
          <ul>
           <% @user.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
          </ul>
        <% end %>
        	<div class="field">
              <%= f.label :name %>
              <%= f.text_field :name %>
          </div>
          <div class="field">
            	<%= attachment_image_tag @user, :profile_image, :fill, 60, 60 %>
            	<%= f.label :profile_image %><br />
            	<%= f.attachment_field :profile_image %>
          </div>
          <div class="field">
              <%= f.label :introduction %>
              <%= f.text_area :introduction %>
          </div>
          <div class="actions">
              <%= f.submit "Update User" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<div class="container">
<p id="notice">
	<%= notice %>
</p>
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg" %>
	<table class="table table-striped">
			<tr>
				<th>name</th>
				<th><%= current_user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= current_user.introduction %></th>
			</tr>
	</table>
	<div class="row">
		<%= link_to edit_user_path(current_user) do %>
			<div class="col-xs-12 btn btn-default"><i class="fas fa-wrench"></i></div>
		<% end %>
	</div>
<h2>New Book</h2>
<%= form_for(@book, url: books_path) do |f| %>
	<div class="field">
		<h4>Title</h4>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<h4>Opinion</h4>
		<%= f.text_area :body %>
	</div>
	<div class="actions">
		<%= f.submit 'Create Book' %>
	</div>
<% end %>
</div>
<div class="col-xs-9">
<h2>Users</h2>
<table class="table table-striped">
	<tr>
		<th>image</th>
		<th>name</th>
		<th></th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td>
			<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>
		</td>
		<td><%= user.name %></td>
		<td><%= link_to "Show", user_path(user.id) %></td>
	</tr>
	<% end %>
</table>
</div>
</div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container">
<p id="notice">
	<%= notice %>
</p>
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback:"no_image.jpg" %>
	<table class="table table-striped">
			<tr>
				<th>name</th>
				<th><%= @user.name %></th>
			</tr>
			<tr>
				<th>introduction</th>
				<th><%= @user.introduction %></th>
			</tr>
	</table>
	<div class="row">
		<%= link_to edit_user_path(@user) do %>
			<div class="col-xs-12 btn btn-default"><i class="fas fa-wrench"></i></div>
		<% end %>
	</div>
<h2>New Book</h2>
<%= form_for(@book, url: books_path) do |f| %>
	<div class="field">
		<h4>Title</h4>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<h4>Opinion</h4>
		<%= f.text_area :body %>
	</div>
	<div class="actions">
		<%= f.submit 'Create Book' %>
	</div>
<% end %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-striped">
	<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
	</tr>
	<% @books.each do |book| %>
	<tr>
		<td>
			<%= link_to user_path(book.user) do %>
			<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback:"no_image.jpg" %>
			<% end %>
		</td>
		<td><%=link_to book.title, book_path(book.id) %></td>
		<td><%= book.body %></td>
	</tr>
	<% end %>
</table>
</div>
</div>
</div>